### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by jaxi** [jplock/docker-zookeeper#11]
I have a project that I’d like to use the docker-zookeeper, however it currently doesn't have a license. 

Would you consider releasing it under an open source license?

**Comment by jplock** [comment]
Whoops, sorry about that.  Yea MIT is probably what I'd do.  Let me add a file.

**Comment by jplock** [comment]
Fixed in https://github.com/jplock/docker-zookeeper/commit/9d5991cca7c03461119f2c72e6c548f85d4384d0
