### ISSUE TITLE
healthcheck shows "unhealthy" for 3.5.5

### ISSUE THREAD

**Issue by ryabko** [jplock/docker-zookeeper#18]
**docker ps** shows that container status is unhealthy
**docker inspect** shows the error happening during a health check:
`sh: is: unknown operand\n`

**Comment by aleboulanger** [comment]
I also have the same issue

**Comment by jplock** [comment]
I republished the docker `3.5.5` and `latest` tags and updated the git `v3.5.5` tag as well to include this commit.
