### ISSUE TITLE
Zookeeper 3.5.2-rc0

### ISSUE THREAD

**Issue by ruimarinho** [jplock/docker-zookeeper#8]
After a long time of development, looks like the 3.5.x release line is finally picking up. Can you tag [3.5.2-rc0](https://github.com/apache/zookeeper/archive/release-3.5.2-rc0.tar.gz) on Docker Hub?

Many thanks!

**Comment by jplock** [comment]
I don't see this version available on the apache mirrors yet.

**Comment by ruimarinho** [comment]
Ok, the versioning scheme is weird, as this was Release Candidate 0 for `3.5.2-alpha`. There is a new build (RC1) which will likely become the _final_ `3.5.2-alpha`.

See the [discussion on the ML](http://mail-archives.apache.org/mod_mbox/zookeeper-dev/201607.mbox/%3cD39B6DB4.4820C%25cnauroth@hortonworks.com%3e).

**Comment by devth** [comment]
`3.5.2-alpha` is available:

- http://archive.apache.org/dist/zookeeper/zookeeper-3.5.2-alpha/
- http://apache.mirrors.pair.com/zookeeper/zookeeper-3.5.2-alpha/

**Comment by ruimarinho** [comment]
Indeed. Can you tag this on Docker Hub @jplock? Many thanks.

**Comment by jplock** [comment]
I just pushed up the `3.5.2-alpha` tag to docker hub
